[package]
name = "git-panic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
colored = "2.0.0"
git2 = "0.17.1"
walkdir = "2.3.3"
